### ISSUE TITLE
测试环境报错{"error":{"code_space":"NFTP-OPEN-API","code":"FORBIDDEN","message":"authentication failed"}}

### ISSUE THREAD

**Issue by yuhang1234** [bianjieai/opb-faq#49]
```
public static void main(String[] args) {
		String avata_api_key = "Dyg0F3Oymt71bN4O7FaQljRpKrhUrzT";
		String avata_api_secret = "OfGg5aKrCmGi5jo2TifmUPMyVfMDfVq";
		String timestamp = System.currentTimeMillis()+"";
		String path = AvataConfig.TEST+AvataConfig.ACCOUNTS;
		String operation_id = getUUIDPrimaryKey();
		
		Map<String, Object> signmap = new HashMap<String, Object>();
		signmap.put("count", 1);
		signmap.put("operation_id", operation_id);
		String signstr = signRequest(AvataConfig.ACCOUNTS,null,signmap,Long.parseLong(timestamp),avata_api_secret);
		
		
		Map<String, String> params = new HashMap<String, String>();
		params.put("count", "1");
		params.put("operation_id", operation_id);
		params.put("X-Api-Key", avata_api_key);
		params.put("X-Signature", signstr);
		params.put("X-Timestamp", timestamp);
		System.out.println("sign:"+ signstr);
		String result = httpPost(path, params);
		System.err.println(result);
	}
	
	/**
	 * 执行HttpPost请求
	 * @param url 请求路径
	 * @param params 参数
	 * @return 结果
	 */
	public static String httpPost(String url, Map<String, String> params){
		CloseableHttpClient httpClient = HttpClients.createDefault();
		HttpPost httpPost =   new HttpPost(url);
		CloseableHttpResponse response = null;
		String result = null;
		try {
			List<NameValuePair> nameValuePairs = new ArrayList<NameValuePair>();
			if (null != params && params.size() > 0) {
				for (Map.Entry<String, String> entry : params.entrySet()) {
					String key = entry.getKey();
					String value = entry.getValue();
					if (key == null || value == null) {
						continue;
					}
					NameValuePair pair = new BasicNameValuePair(key, value);
					nameValuePairs.add(pair);
				}
			}
			httpPost.setEntity(new UrlEncodedFormEntity(nameValuePairs,"UTF-8"));
			httpPost.setHeader("Content-type", "application/json");
			httpPost.setHeader("X-Api-Key", params.get("X-Api-Key"));
			httpPost.setHeader("X-Signature", params.get("X-Signature"));
			httpPost.setHeader("X-Timestamp", params.get("X-Timestamp"));
			// 执行请求
			response = httpClient.execute(httpPost);
			HttpEntity entity = response.getEntity();
			if (null != entity) {
				result = EntityUtils.toString(entity, "UTF-8");
				EntityUtils.consume(entity);
			}
		} catch (IOException e) {
			e.printStackTrace();
		} finally {
			try {
				if (response != null) {
					response.close();
				}
			} catch (IOException e) {
				e.printStackTrace();
				System.out.println("请求通信[\" + reqURL + \"]时网络时，关闭异常,堆栈轨迹如下");
			}
			httpPost.releaseConnection();
		}
		return result;
	}
```
```
public static String signRequest(String path, Map<String, Object> query, Map<String, Object> body, long timestamp, String apiSecret) {
        Map<String, Object> paramsMap = new HashMap();

        paramsMap.put("path_url", path);

        if (query != null && !query.isEmpty()) {
//            query.forEach((key, value) -> paramsMap.put("query_" + key, value));
        	String key = "";
        	Object value = "";
            for(Map.Entry<String, Object> entry : query.entrySet()){
            	key = entry.getKey();
            	value = entry.getValue();
                paramsMap.put("query_" + key, value);
            }
        }

        if (body != null && !body.isEmpty()) {
//            body.forEach((key, value) -> paramsMap.put("body_" + key, value));
            String key = "";
        	Object value = "";
            for(Map.Entry<String, Object> entry : body.entrySet()){
            	key = entry.getKey();
            	value = entry.getValue();
                paramsMap.put("body_" + key, value);
            }
        }

        // 将请求参数序列化为排序后的 JSON 字符串
        String jsonStr = JSON.toJSONString(paramsMap);

        // 执行签名
        String signature = sha256Sum(jsonStr + String.valueOf(timestamp) + apiSecret);

        return signature;
    }
```

**Comment by ajiang55** [comment]
// 将请求参数序列化为排序后的 JSON 字符串
        String jsonStr = JSON.toJSONString(paramsMap, SerializerFeature.MapSortField);
序列化时需要传入一个排序参数

**Comment by yuhang1234** [comment]
java.io.IOException: Server returned HTTP response code: 403 for URL: https://stage.apis.avata.bianjie.ai/v1beta1/accounts
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at com.perssoft.avata.HttpPostJson.sendPost(HttpPostJson.java:61)
	at com.perssoft.avata.AvataUtils.main(AvataUtils.java:49)

**Comment by yuhang1234** [comment]
> // 将请求参数序列化为排序后的 JSON 字符串 String jsonStr = JSON.toJSONString(paramsMap, SerializerFeature.MapSortField); 序列化时需要传入一个排序参数
报错了
java.io.IOException: Server returned HTTP response code: 403 for URL: https://stage.apis.avata.bianjie.ai/v1beta1/accounts
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
	at com.perssoft.avata.HttpPostJson.sendPost(HttpPostJson.java:61)
	at com.perssoft.avata.AvataUtils.main(AvataUtils.java:49)
