### ISSUE TITLE
// 将请求参数序列化为排序后的 JSON 字符串 String jsonStr = JSON.toJSONString(paramsMap, SerializerFeature.MapSortField); 序列化时需要传入一个排序参数 

### ISSUE THREAD

**Issue by BAige88** [bianjieai/opb-faq#57]
// 将请求参数序列化为排序后的 JSON 字符串 String jsonStr = JSON.toJSONString(paramsMap, SerializerFeature.MapSortField); 序列化时需要传入一个排序参数
报错了
java.io.IOException: Server returned HTTP response code: 403 for URL: https://stage.apis.avata.bianjie.ai/v1beta1/accounts
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268)
at com.perssoft.avata.HttpPostJson.sendPost(HttpPostJson.java:61)
at com.perssoft.avata.AvataUtils.main(AvataUtils.java:49)

**Comment by BAige88** [comment]
麻烦老师  感谢老师  平台现已做完了 只等着对接好上链上线平台了  特着急

**Comment by ajiang55** [comment]
鉴权参数错误,鉴权不通过,接口返回403

**Comment by ajiang55** [comment]
参考[https://github.com/bianjieai/opb-faq/issues/13](url)

**Comment by BAige88** [comment]
创建链账户时报错{"error":{"code_space":"ACCOUNTS","code":"INTERNAL_ERROR","message":"internal error"}} #62
